name: Deploy Laravel 11 to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, tokenizer, xml, gd, pdo_mysql

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Laravel Setup
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Ensure Laravel directories exist and have correct permissions
        run: |
          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      - name: Zip the app
        run: |
          zip -r app.zip . -x '*.git*' '*.github*' 'tests/*' 'node_modules/*' 'storage/logs/*' 'vendor/bin/*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_ELASTICBEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ELASTICBEANSTALK_ENVIRONMENT_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: "v-${{ github.run_number }}"
          deployment_package: app.zip
          wait_for_deployment: true
          use_existing_version_if_available: true
